# Generated by Django 4.2 on 2025-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='product/')),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
