# Generated by Django 4.2 on 2025-05-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product_quantity_product_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('1kg', '1 KG'), ('0.5kg', '0.5 KG'), ('1', '1')], max_length=128),
        ),
    ]
