# Generated by Django 4.2 on 2025-05-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart_cartitem_cart_unique_open_cart_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='cart_item_unique'),
        ),
    ]
